# Generated by Django 4.0.4 on 2023-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_text',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
