# Generated by Django 4.0.4 on 2023-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_news_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(max_length=1000),
        ),
    ]
