# Generated by Django 4.0.4 on 2023-06-11 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_alter_news_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=250)),
                ('sent_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='date sent')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.news')),
            ],
        ),
    ]
