# Generated by Django 4.0.4 on 2023-06-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_news_news_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_short_title',
        ),
    ]
